version: "3.9"
services:
    proxy:
        image: nginx:latest
        container_name: proxy
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            -   frontend
            -   backend
        ports:
            - "8008:8000"
        expose:
            - "8008"
        depends_on:
            -   python
            -   staticfiles
        restart: on-failure

    python:
        build: ./backend
        container_name: python
        command: gunicorn djrestauth.wsgi -b 0.0.0.0:81
        ports:
            - "81"
        expose:
            - "81"
        volumes:
            - ./backend:/code
        networks:
            -   backend
            -   hidden
        restart: on-failure

    staticfiles:
        image: nginx:latest
        container_name: staticfiles
        volumes:
            - ./frontapp/dist/app:/www/app
            - ./frontapp/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            -   frontend
        ports:
            - "80"
        expose:
            - "80"
        restart: on-failure

    db:
        image: postgres:latest
        container_name: database
        volumes:
            -   dbData:/var/lib/postgresql/data
        environment:
            -   POSTGRES_PASSWORD=mysecretpassword
            -   POSTGRES_USER=defalt91
            -   PGPASSWORD=mysecretpassword
            -   POSTGRES_DB=djangoDB
            -   POSTGRES_HOST_AUTH_METHOD="true"
            -   PGDATA=/var/lib/postgresql/data
        networks:
            -   hidden
        ports:
            - "5432"
        restart: on-failure
networks:
    frontend:
        driver: bridge
        name: frontend_network
        internal: false
    backend:

        driver: bridge
        name: backend_network
        internal: false
    hidden:
        driver: bridge
        name: hidden_network
        internal: true
volumes:
    dbData:
        name: postgreSql
