version: "3.9"
services:
    proxy:
        image: nginx:latest
        container_name: proxy
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./cert/localhost/localhost.crt:/etc/ssl/certs/nginx-selfsigned.crt
            - ./cert/localhost/localhost.decrypted.key:/etc/ssl/private/nginx-selfsigned.key
        networks:
            -   frontend
            -   backend
        ports:
            - "443:443"
            - "80:80"
        expose:
            - "8008"
        depends_on:
            -   python
            -   staticfiles
        restart: on-failure

    python:
        image: python-django-pip-image
        env_file: dev.env
        container_name: python
        command: gunicorn djrestauth.wsgi -b 0.0.0.0:81
        ports:
            - "81"
        expose:
            - "81"
        volumes:
            - ./backend:/code
        networks:
            -   backend
            -   hidden
        restart: on-failure

    staticfiles:
        image: nginx:latest
        container_name: staticfiles
        volumes:
            - ./frontapp/dist/app:/www/app
            - ./frontapp/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            -   frontend
        ports:
            - "80"
        expose:
            - "80"
        restart: on-failure

    db:
        image: postgres:alpine
        container_name: database
        volumes:
            -   dbData:/var/lib/postgresql/data
        environment:
            -   "POSTGRES_USER=SuperUesr"
            -   "POSTGRES_PASSWORD=<<0012A96s21g39>>"
            -   "POSTGRES_DB=postgres"
            -   "PGPASSWORD=63A67s411g"
            -   "PGDATA=/var/lib/postgresql/data"
        networks:
            -   hidden
        ports:
            - "5432"
        expose:
            - "5432"
networks:
    frontend:
        driver: bridge
        name: frontend_network
        internal: false
    backend:

        driver: bridge
        name: backend_network
        internal: false
    hidden:
        driver: bridge
        name: hidden_network
        internal: true
volumes:
    dbData:
        name: rest_authpsql_volume
