version: "3.9"
services:
    proxy:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8008:8000"
        expose:
            - "8008"
    python:
        build: ./backend
        command: gunicorn djrestauth.wsgi -b 0.0.0.0:81
        ports:
            - "81"
        expose:
            - "81"
        volumes:
            - ./backend:/code
    staticfiles:
        image: nginx:latest
        volumes:
            - ./frontapp/dist/app:/www/app
            - ./frontapp/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80"
        expose:
            - "80"